const ROOMS = [
  {
    id: "standard-double",
    name: "Standard Double",
    category: "Standard",
    pricePerNight: 3500,
    capacity: "2-3 guests",
    beds: "1 Queen Bed",
    size: "280 sq ft",
    amenities: ["AC", "WiFi", "TV", "Hot Water", "Desk"],
    description: "Cozy room with queen bed, perfect for couples seeking a comfortable and affordable stay with all essential amenities.",
    imageUrl: "https://images.unsplash.com/photo-1631049307038-da31ec3d517c?w=600&h=400&fit=crop",
  },
  {
    id: "deluxe-double",
    name: "Deluxe Double",
    category: "Deluxe",
    pricePerNight: 5500,
    capacity: "2-4 guests",
    beds: "1 King Bed",
    size: "380 sq ft",
    amenities: ["AC", "WiFi", "TV", "Balcony", "Mini Bar", "Desk"],
    description: "Spacious deluxe room with king bed and private balcony overlooking the tropical gardens.",
    imageUrl: "https://images.unsplash.com/photo-1582719471384-894fbb16e074?w=600&h=400&fit=crop",
  },
  {
    id: "suite",
    name: "Premium Suite",
    category: "Suite",
    pricePerNight: 7500,
    capacity: "2-4 guests",
    beds: "1 King Bed",
    size: "520 sq ft",
    amenities: ["AC", "WiFi", "TV", "Balcony", "Mini Bar", "Hot Tub", "Sitting Area"],
    description: "Luxurious suite with separate living area, premium furnishings, and stunning views.",
    imageUrl: "https://images.unsplash.com/photo-1615874959375-5d0c180d9b1b?w=600&h=400&fit=crop",
  },
  {
    id: "premium-suite",
    name: "Executive Suite",
    category: "Premium Suite",
    pricePerNight: 9500,
    capacity: "2-4 guests",
    beds: "1 King Bed",
    size: "650 sq ft",
    amenities: ["AC", "WiFi", "TV", "Balcony", "Mini Bar", "Jacuzzi", "Sitting Area", "Dining"],
    description: "Ultra-luxurious suite with premium amenities, private jacuzzi, and panoramic views.",
    imageUrl: "https://images.unsplash.com/photo-1578073366220-a0de08b4b553?w=600&h=400&fit=crop",
  },
  {
    id: "villa-2br",
    name: "Beachfront Villa",
    category: "Villa",
    pricePerNight: 11000,
    capacity: "4-6 guests",
    beds: "2 King Beds",
    size: "900 sq ft",
    amenities: ["AC", "WiFi", "Pool Access", "Kitchen", "2 Bedrooms", "Living Room", "Patio"],
    description: "Spacious 2-bedroom villa with direct beachfront access, private patio, and full kitchen.",
    imageUrl: "https://images.unsplash.com/photo-1512207736139-c2d7c588f7d7?w=600&h=400&fit=crop",
  },
  {
    id: "presidential-villa",
    name: "Presidential Villa",
    category: "Suite+",
    pricePerNight: 15000,
    capacity: "4-8 guests",
    beds: "3 King Beds",
    size: "1400 sq ft",
    amenities: ["AC", "WiFi", "Private Pool", "Kitchen", "3 Bedrooms", "Concierge", "Butler Service"],
    description: "Exclusive presidential villa with private pool, dedicated butler, and 24/7 concierge service.",
    imageUrl: "https://images.unsplash.com/photo-1540932239986-310128078ceb?w=600&h=400&fit=crop",
  },
];

const SAMPLE_BOOKINGS = [
  {
    id: "RB001",
    guestName: "Rajesh Kumar",
    email: "rajesh.kumar@email.com",
    phone: "9876543210",
    room: "deluxe-double",
    checkIn: "2026-08-15",
    checkOut: "2026-08-17",
    nights: 2,
    guests: 2,
    totalPrice: 11550,
    status: "Pending",
    specialRequests: "Late check-in please",
    createdDate: "2026-07-20",
  },
  {
    id: "RB002",
    guestName: "Priya Sharma",
    email: "priya.sharma@email.com",
    phone: "9876543211",
    room: "suite",
    checkIn: "2026-08-18",
    checkOut: "2026-08-20",
    nights: 2,
    guests: 2,
    totalPrice: 15750,
    status: "Confirmed",
    specialRequests: "",
    createdDate: "2026-07-18",
  },
  {
    id: "RB003",
    guestName: "Amit Patel",
    email: "amit.patel@email.com",
    phone: "9876543212",
    room: "villa-2br",
    checkIn: "2026-08-22",
    checkOut: "2026-08-25",
    nights: 3,
    guests: 5,
    totalPrice: 34650,
    status: "Confirmed",
    specialRequests: "Need extra towels and pillows",
    createdDate: "2026-07-15",
  },
  {
    id: "RB004",
    guestName: "Neha Singh",
    email: "neha.singh@email.com",
    phone: "9876543213",
    room: "deluxe-double",
    checkIn: "2026-08-28",
    checkOut: "2026-08-30",
    nights: 2,
    guests: 2,
    totalPrice: 11550,
    status: "Pending",
    specialRequests: "Anniversary celebration",
    createdDate: "2026-07-22",
  },
  {
    id: "RB005",
    guestName: "Vikram Bhat",
    email: "vikram.bhat@email.com",
    phone: "9876543214",
    room: "standard-double",
    checkIn: "2026-09-01",
    checkOut: "2026-09-03",
    nights: 2,
    guests: 2,
    totalPrice: 7350,
    status: "Confirmed",
    specialRequests: "",
    createdDate: "2026-07-10",
  },
  {
    id: "RB006",
    guestName: "Anjali Gupta",
    email: "anjali.gupta@email.com",
    phone: "9876543215",
    room: "premium-suite",
    checkIn: "2026-09-05",
    checkOut: "2026-09-08",
    nights: 3,
    guests: 3,
    totalPrice: 29925,
    status: "Cancelled",
    specialRequests: "Early check-in if possible",
    createdDate: "2026-07-05",
  },
];

const REVIEWS = [
  {
    name: "Rajesh Kumar",
    location: "Mumbai",
    rating: 5,
    comment: "Absolutely amazing experience! The staff was wonderful, rooms were pristine, and the views were breathtaking. Will definitely come back.",
    date: "Mar 2026",
    avatar: "RK",
  },
  {
    name: "Priya Sharma",
    location: "Bangalore",
    rating: 5,
    comment: "Perfect getaway for our anniversary. The Premium Suite was luxurious and the service was impeccable. Highly recommended!",
    date: "Feb 2026",
    avatar: "PS",
  },
  {
    name: "Amit Patel",
    location: "Delhi",
    rating: 4,
    comment: "Great family vacation spot. Kids loved the pool and the villa was spacious. Food could be slightly better but overall excellent.",
    date: "Jan 2026",
    avatar: "AP",
  },
  {
    name: "Sarah & Tom Williams",
    location: "London, UK",
    rating: 5,
    comment: "We traveled all over India and this was by far the best resort experience. The Presidential Villa was out of this world!",
    date: "Dec 2025",
    avatar: "SW",
  },
  {
    name: "Deepa Menon",
    location: "Kochi",
    rating: 5,
    comment: "A hidden gem! The heritage bungalow had so much character. The staff went above and beyond to make our stay special.",
    date: "Nov 2025",
    avatar: "DM",
  },
];

const RESORT_INFO = {
  name: "Coastal Haven Resort",
  tagline: "Where the Ocean Meets Luxury",
  phone: "+91 98765 43210",
  email: "info@coastalhaven.com",
  address: "123, Coastal Road, Palolem, South Goa 403702",
  social: {
    instagram: "#",
    facebook: "#",
    twitter: "#",
  },
};
